### ISSUE TITLE
[QUESTION] Nested arrays support

### ISSUE THREAD

**Issue by dominicegginton** [iamguid/ngx-mf#1]
My Model:

```ts
export interface Model {
  foo: {
    bar: string,
    baz: string[],
  }[],
}
```

The form group type I want:

```ts
interface ... {
  foo: FormArray<{ bar: FormControl<string>, baz: FormArray<string> }>
}
```

This this possible with **ngx-mf**?

**Comment by iamguid** [comment]
I think, yes, but it looks like a bug, because it don't work, i will fix it today, thank you for issue report.

**Comment by iamguid** [comment]
Sure, you can, annotation should be `{ foo: [{ baz: 'array' }] }` full example you can find here https://stackblitz.com/edit/angular-ngx-mf-gqrrau?file=src/app/app.component.ts

**Comment by iamguid** [comment]
But i found 1 small bug, in line https://stackblitz.com/edit/angular-ngx-mf-gqrrau?file=src%2Fapp%2Fapp.component.ts%3AL34,src%2Fapp%2Fmodel.ts type should be nullable, but in that example it nonNullable

**Comment by iamguid** [comment]
I fix it today

**Comment by dominicegginton** [comment]
Awesome thank you, this is what I was looking for 👍
