### ISSUE TITLE
Not working without tsconfig strictNullChecks

### ISSUE THREAD

**Issue by jmoghaddam** [iamguid/ngx-mf#10]
Hi,
Seems that, its working only with strictNullChecks set to true.
In my case, setting strictNullChecks to true breaks build on other lib dependencies.
Thank u

**Comment by iamguid** [comment]
Sorry, I was busy, I will fix it today. Thank you for PR

**Comment by iamguid** [comment]
New version (v4.1.1) is published, you can take it from npm
