### ISSUE TITLE
How can we recursively exclude a field?

### ISSUE THREAD

**Issue by ghost** [iamguid/ngx-mf#12]
_TL;DR_: Is there an easy way to exclude a certain field recursively from the form?

---

First of all, thanks a ton for the library!

We're using GraphQL so the data returned from the backend looks like this:

``` json
{
  "id": 123,
  "__typename": "Player",
  "name": "graham",
  "scores": [
    { "round": 1, "score": 200, "__typename": "PlayerScore" },
    { "round": 2, "score": 250, "__typename": "PlayerScore" }
  ]
}
```

but the payload to the backend should not have the `__typename` properties.

So far we can go wild with the `Replace`, removing the `__typename` property from every level but we would prefer having something like `GraphQLFormModel` that is equivalent to the `FormModel` but skips the `__typename` property. Is there a way to write such metatype as a wrapper around `FormModel`, or we have to copy the source in order to be able to do this?

**Comment by iamguid** [comment]
Hello!, thank you for open the issue!

Regarding your question, of course you can, with metatype, without any changes in the library. There is small example with your scenario.

https://stackblitz.com/edit/angular-ngx-mf-renugu?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fuser.model.ts,package.json

You just need to use this generic type on top of your model:

```ts
export type HideField<TModel, TField extends string> = {
  [key in keyof Omit<TModel, TField>]: TModel[key] extends Array<
    infer TInferredArrayValueType
  >
    ? Array<HideField<TInferredArrayValueType, TField>>
    : TModel[key] extends Record<string, any>
    ? HideField<TModel[key], TField>
    : TModel[key];
};
```

**Comment by iamguid** [comment]
Please, give me a star for that work :)
