### ISSUE TITLE
Support shorthand form builder types

### ISSUE THREAD

**Issue by Harpush** [iamguid/ngx-mf#15]
In form builder you can pass actual values and not form controls to everything expect form controls of arrays and of course actual form groups/areays.
In the form builder type I think it should allow passing a regular value (unless it an array) instead of always requiring to create form controls.
Of course I could also pass a form control if I want validations

**Comment by iamguid** [comment]
Could you please provide some code example and expected behavior?

**Comment by iamguid** [comment]
If you mean array syntax, like
```
fb.group({
    name: ['', Validators.required],
    quantity: [1, [Validators.required, Validators.min(1)]],
});
```
This is not supported and is not planned for the near future.

**Comment by Harpush** [comment]
I meant:
```ts
fb.group({
    name: 'abc',
    quantity: 1
});
```
VS
```ts
fb.group({
    name: fb.control('abc'),
    quantity: fb.control(1)
});
```

**Comment by iamguid** [comment]
Need to think about this propose, but it is not a type script related thing, need to write a js runtime wrapper for this. Ok, i'll think about it, thank you!
