### ISSUE TITLE
Latest version not published to npm

### ISSUE THREAD

**Issue by Harpush** [iamguid/ngx-mf#16]
The latest version 4.1.1 isn't the one in master - when will the new version get published?

**Comment by iamguid** [comment]
Today I will.

**Comment by Harpush** [comment]
Did it happen?

**Comment by gk-bbai** [comment]
~It did.~ I misunderstood.

**Comment by Harpush** [comment]
> It did.

I don't see it though - link to npm?

**Comment by gk-bbai** [comment]
Sorry, I misunderstood.  The title says "latest version" isn't published, so I thought you were saying 4.1.1 wasn't published to npm.

**Comment by gk-bbai** [comment]
Slightly related, package.json still says version `4.1.0`:

https://github.com/iamguid/ngx-mf/blob/master/package.json#L3

**Comment by ManuelRauber** [comment]
> Today I will.

@iamguid Can you please update it if it is ready?

**Comment by iamguid** [comment]
Sorry guys I was really busy, and I quit from the company where I was working on this project. Now I have time to work on this project. It is not abandoned, just I thought that nobody use it. Now I'll put things in order. And answer for questions and fix bugs. Thank you for waiting, sorry for this.

**Comment by iamguid** [comment]
It is published (v5.2.0), a new type FormType is available in latest version, documentation is up to date now, sorry for waiting.

new playground is available on this page https://stackblitz.com/edit/ngx-mf-playground?file=src%2Fmain.ts

v5.0.0 and v5.1.0 is broken for some reason, ignore it.
