### ISSUE TITLE
FormType not available

### ISSUE THREAD

**Issue by gk-bbai** [iamguid/ngx-mf#18]
The README says to use `FormType`, but this is not an exported property of the library.

### Expected Behavior

README should be updated with the latest changes or FormType should be made available for import.

**Comment by gk-bbai** [comment]
This is probably due to https://github.com/iamguid/ngx-mf/issues/16.

**Comment by iamguid** [comment]
Yes, it is not published yet, sorry for this. I'll publish today if it possible.
