### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Rhobal** [iamguid/ngx-mf#19]
Please add information to the read.me how to see the resulting type in the way you show the form type in the readme.

I tried this approach: https://stackoverflow.com/a/70861557/2080575 both in IntelliJ and in typescriptlang.org

I have a complex model and it's hard to make the result of FormBuilder.group match the type of FormType<Model> without seeing the calculated type of the FormType<> Logic

**Comment by iamguid** [comment]
Hello, Rhobal! I didn't use any specific tools and approaches to show form type, in readme I just crafted it by hands. But I improved readability and usability of the library, as you can see in this example https://github.com/iamguid/ngx-mf/blob/master/tests/example.test.mts#L8

Just put your model in FormType `type YourForm = FormType<YourModel>` and you will get a tree of your controls, where

`YourForm[T]` - is your root type of your form group aka `FormGroup<...>`
`YourForm[G]` - is your root object of your form group aka `{ a: FormControl<...>, b: FormArray<...> }`
`YourForm[I]` - is your array item type of your form (only if it is form array) aka `FormControl<...>`
`YourForm['a']` - is your 'a' node from the root of your FormType aka `{ b: [T] or [G] or [I] or other keys inside YourForm['a'] }`

And you should use it when you use YourForm in every FormGroup node, like

```TypeScript
// Define your root form
const formRoot: YourForm[T] = fb.group<YourForm[G]>({
    //                                     ^ this is important thing that will help you to see all errors in current node, if something wrong.       
    // define your controls
})

// Define your child form
const formA: YourForm['a'][T] = fb.group<YourForm['a'][G]>({
    //                                         ^ This is also important
    some_invalid_control: fb.control('invalid type')
    //                                    ^ As a result you will see readable error here
})
```

**Comment by Rhobal** [comment]
Thanks, I will try to apply these tricks when I convert my next UntypedFormGroup...
