### ISSUE TITLE
InferModeFromModel and InferModeNonNullable not working correctly

### ISSUE THREAD

**Issue by ebiermann** [iamguid/ngx-mf#6]
InferModeFromModel does not seem to infer nullability correctly. In the following example I would expect the FormControl derived from nonNullable to be `FormControl<string>` instead of `FormControl<string | null>`.

InferModeNonNullable on the other hand seems to change the type of nullable from `FormControl<string | null>` to `FormControl<string>`. I would expect InferModeNonNullable to only make testFg.controls.nullable non-optional instead.

```  typescript
  it('NullTest', () => {
    interface NullTest {
      readonly nonNullable: string;
      readonly nullable: string | null;
    }

    type TestForm = FormModel<NullTest, null, InferModeFromModel & InferModeNonNullable>;

    // creation
    const testFg: TestForm = new FormGroup<TestForm['controls']>({
      nonNullable: new FormControl<string>('nonNullable'),
      nullable: new FormControl<string | null>('')
    });

    // different form interactions that should work given the interface and form type
    testFg.controls.nullable.reset(null);
    const nullTest: NullTest = testFg.getRawValue();
    testFg.reset({
      nullable: null,
      nonNullable: 'nonNullable'
    })
  });
```

I haven't found any working combination of infer modes that makes this example work the way I want it to i.e. non-nullable controls that are typed `<string | null>` and `<string>` respectively.

**Comment by iamguid** [comment]
Ok, thx for issue I'll check in weekend

**Comment by iamguid** [comment]
So the right InferMode is FromModel, try it

There is a working example

```typescript
it('NullTest https://github.com/iamguid/ngx-mf/issues/6', () => {
    interface NullTest {
      nonNullable: string;
      nullable: string | null;
    }

    type TestForm = FormModel<NullTest, null, InferModeFromModel>;

    const fb = new FormBuilder();

    // creation
    const testFg: TestForm = fb.group<TestForm['controls']>({
        nonNullable: fb.nonNullable.control<string>('nonNullable'),
        nullable: fb.control<string | null>('')
    });

    // different form interactions that should work given the interface and form type
    testFg.controls.nullable.reset(null);
    const nullTest: NullTest = testFg.getRawValue();
    testFg.reset({
        nullable: null,
        nonNullable: 'nonNullable'
    })
});
```

**Comment by ebiermann** [comment]
Thanks for the working example I believe the confusion comes from an error in the documentation:

>     InferModeFromModel - infer all from model (optionals and nullability)
>     InferModeFromModel & InferModeNonNullable - infer optionals from model, and all controls will be all nonnullable
>     InferModeFromModel & InferModeNullable - infer optionals from model, and all controls will be nullable
>     InferModeOptional & InferModeNonNullable - makes all fields optional and all controls will be nonnullable
>     InferModeOptional & InferModeNullable - makes all fields optional, and all controls will be nnullable
>     InferModeOptional & InferModeFromModel - makes all fields optional, and controls infer nullability from model
>     InferModeRequired & InferModeNonNullable - makes all fields required, and all controls will be nonnullable
>     InferModeRequired & InferModeNullable - makes all fields required, and all controls will be nnullable
>     InferModeRequired & InferModeFromModel - makes all fields required, and controls infer nullability from model

Optional and Required are the ones that influence controls while Nullable and NonNullable influence the model values inside the controls.

**Comment by iamguid** [comment]
Ok, i'll fix documentation then, but you can also check tests it is full of examples of behavior https://github.com/iamguid/ngx-mf/blob/master/tests/infermode.test.ts
