### ISSUE TITLE
Annotations are not type safe

### ISSUE THREAD

**Issue by ManuelRauber** [iamguid/ngx-mf#7]
Hi!

I've got the following issue:

```ts
interface Model {
    a: string;
    b: string;
}

// Works
type ModelForm1 = FormModel<Model>;

// Works
type ModelForm2 = FormModel<Model, { b: Replace<FormControl<number | null>> }>;

// "Works" by having an error that { c ... } does not satisfy the constraint.
type ModelForm3 = FormModel<Model, { c: Replace<FormControl<number | null>> }>; 

// Works, no error
type ModelForm4 = FormModel<Model, { b: Replace<FormControl<number | null>>; c: Replace<FormControl<string | number>> }>; 
```

As you can see, that `ModelForm3` correctly shows an error, that `c` does not satisfy the `TAnnotation` constraint.

However, if you, like in `ModelForm4` have another valid annotation in there, you can add any other without the type showing an error. 

Unfortunately, my TS type voodoo is not good enough to spot the error myself and make a PR. I hope you have an idea, if that is fixable. :)

Thanks!

**Comment by iamguid** [comment]
Hello, thank you for feedback, yes I know about that issue, but it is typescript limitation. There is an example how typescript works in that case https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgjFAvFA3lAhgLigZ2AJwEsA7AcwBooAjbYgVwFsqJ8oBfAWAChRJYAmADwwoEAB7AIxACY5YcAHxJUUAMbYRnHuGgwAzMphC0WXARIVqtRs3yV11APaOANhHTF2CoA

Sorry it is not fixable
